[project]
name = "concord"
version = "1.0.4"
description = "High-performance Python library for concurrently executing asynchronous requests"
requires-python = ">=3.9"
dependencies = [
    "curl-cffi>=0.10.0"
]
